### ISSUE TITLE
The warning message cannot be displayed correctly in dark mode

### ISSUE THREAD

**Issue by Rustin170506** [Rustin170506/tokio-console-web#320]
The warning message cannot be displayed correctly in dark mode.

<img width="1651" alt="image" src="https://github.com/user-attachments/assets/d4def6c0-f3f9-4565-8015-ebafb770eaa1">
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/8a9a3605-e714-4834-b6d4-967de6fd6a64">

**Comment by LucioPalmucci** [comment]
Assign it to me @Rustin170506
